# Travis CI configuration for autojump
language: python
sudo: false

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "pypy3"

# Install dependencies
install:
  - pip install tox tox-coverage
  - pip install pytest

# Run tests
script:
  - tox

# Test coverage
after_success:
  - coverage combine
  - coverage report -m
  - codecov

# Caching
cache:
  pip: true
  directories:
    - $HOME/.cache/pip

# Notifications
notifications:
  email:
    on_success: change
    on_failure: always

# Only build on push and pull requests
branches:
  only:
    - master
    - main
    - /^v\d+\..*$/

# Matrix
matrix:
  fast_finish: true
  allow_failures:
    - python: "pypy3"
